[theme]
base = "dark"
primaryColor = "#25DCD1"
backgroundColor = "#000000"          # App-Hintergrund
secondaryBackgroundColor = "#0f1c2e" # Sidebar/Karten
textColor = "#FFFFFF"                # hoher Kontrast
font = "sans serif"

# --- Server/Runtime ---
[server]
# Für Docker lausche auf allen Interfaces
address = "0.0.0.0"
port = 8501
headless = true
# CORS Cross-Origin Resource Sharing
enableCORS = true
# XSRF-Schutz aktiv lassen
enableXsrfProtection = true
# Optional: vermeidet ständige Reruns bei Artefakt-Updates
folderWatchingBlacklist = ["artifacts", ".git", ".venv", "__pycache__"]

# --- Client/UI ---
[client]
# "viewer" versteckt Dev-Toolbar; "auto" zeigt sie nur lokal
toolbarMode = "viewer"
showErrorDetails = true

# --- Browser/Telemetrie ---
[browser]
# Keine Nutzungsstatistiken senden (optional)
gatherUsageStats = false

# --- Logging ---
[logger]
level = "info"